FROM mysql:9

COPY ./vacationsagency_likes.sql /docker-entrypoint-initdb.d

COPY ./vacationsagency_users.sql /docker-entrypoint-initdb.d

COPY ./vacationsagency_vacations.sql /docker-entrypoint-initdb.d

